# Generated by Django 5.0.6 on 2024-05-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masked_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
