# Generated by Django 5.0.6 on 2024-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_maskedimage_alter_imageupload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('governorate', models.CharField(max_length=50)),
                ('inventoryID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=100)),
                ('userAddress', models.CharField(max_length=200)),
                ('ProductName', models.CharField(max_length=50)),
                ('Productprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adminName', models.CharField(max_length=100)),
                ('adminEmail', models.EmailField(max_length=100)),
                ('adminAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventoryID', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=50)),
                ('productnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('governorate', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MaskedImage',
        ),
    ]
