# Generated by Django 5.0.6 on 2024-06-30 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_order_accepted_order_productnum_order_totalprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease_Treatment',
            fields=[
                ('diseaseName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('organic', models.TextField(max_length=1000)),
                ('chemical', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryID', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='inventoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.inventory'),
        ),
        migrations.AlterField(
            model_name='products_inventory',
            name='inventoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.inventory'),
        ),
    ]
