# Generated by Django 5.0.6 on 2024-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_disease_treatment_inventory_delete_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userType',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
