# Generated by Django 5.0.6 on 2024-07-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_governorate_rename_productname_order_productname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governorate',
            old_name='name',
            new_name='govername',
        ),
    ]
