# Generated by Django 5.0.6 on 2024-07-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_rename_name_governorate_govername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adminEmail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userEmail',
        ),
        migrations.AlterField(
            model_name='user',
            name='governorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.governorate'),
        ),
    ]
