# Generated by Django 5.0.6 on 2024-07-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_order_adminemail_remove_order_useremail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='governorate',
            new_name='govername',
        ),
    ]
