# Generated by Django 5.0.6 on 2024-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_rename_governorate_user_govername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governorate',
            name='govername',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Beheira', 'Beheira'), ('Beni Suef', 'Beni Suef'), ('Dakahlia', 'Dakahlia'), ('Damietta', 'Damietta'), ('Faiyum', 'Faiyum'), ('Gharbia', 'Gharbia'), ('Ismailia', 'Ismailia'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Luxor', 'Luxor'), ('Matruh', 'Matruh'), ('Minya', 'Minya'), ('Monufia', 'Monufia'), ('New Valley', 'New Valley'), ('North Sinai', 'North Sinai'), ('Port Said', 'Port Said'), ('Qalyubia', 'Qalyubia'), ('Qena', 'Qena'), ('Red Sea', 'Red Sea'), ('Sharqia', 'Sharqia'), ('Sohag', 'Sohag'), ('South Sinai', 'South Sinai'), ('Suez', 'Suez'), ('Suezwww', 'Suezwww')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
