# Generated by Django 5.0.6 on 2024-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease_treatment',
            name='productName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='productName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products_inventory',
            name='productName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
