# Generated by Django 5.0.6 on 2024-07-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_disease_treatment_productname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_inventory',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='adminAddress',
            field=models.CharField(default='Admin Address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='adminName',
            field=models.CharField(default='Admin Name', max_length=100, null=True),
        ),
    ]
