# Generated by Django 5.0.6 on 2024-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sound', models.FileField(upload_to='sounds/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
