# Generated by Django 5.0.6 on 2024-07-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_soundfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundfile',
            name='title',
        ),
    ]
